### ISSUE TITLE
Are you positive it will always be the last script?

### ISSUE THREAD

**Issue by theo-armour** [paulmasson/mathcell#11]
I am looking at this line:

> var parent = document.scripts[ document.scripts.length - 1 ].parentNode;

I am wondering is this really safe? I guess it must be otherwise it would already have failed on you. 

So - just thinking out loud:

Another way of handling this might be to give the script an id. Yes this means the author will have to come up with an id. The idea that ids must be unique is a known rule in web dev so perhaps not too onerous and it might provide a quicker understanding of what is going on.

- tested only very lightly

````
<div class="mathcell" style="height: 4in">
	<script id=woozle >
		//var parent = document.scripts[ document.scripts.length - 1 ].parentNode;
		var parent = woozle.parentNode;
		var id = generateId();
		parent.id = id;
````

**Comment by paulmasson** [comment]
If you remember one of our dinners two years ago, I was having a major issue at the time setting `id` from `document.scripts.length` because MathJax loads and unloads scripts while processing the page. This created a problem because the value changed between retrieving the parent and then setting a new variable. I think that at the time the parent is retrieved the value is stable, otherwise I would have seen additional issues in the intervening two years.

I want to keep automatic `id`s, mostly for my own convenience, because coming up with unique values in the processing of writing a long HTML page is not necessarily simple.

**Comment by theo-armour** [comment]
All good.

I have thoughts about id naming and numbering schemes and reasons for doing so. Something to chat about next time we meet.

OK to close?

**Comment by paulmasson** [comment]
Just found a property named `currentScript`. Perhaps more stable.

**Comment by theo-armour** [comment]
oh wow fascinating. the DOM gets incredibler and Incredibler

https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript

**Comment by theo-armour** [comment]
and I was thinking of accessing CSS counters via JavaScript - since you
already have used counters elsewhere

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters

**Comment by paulmasson** [comment]
@theo-armour trying out `currentScript` for stability and conciseness

@axkr you may want to update your MathCell template [accordingly](https://github.com/paulmasson/mathcell/blob/master/docs/starting.html)
